DELIMITER //
CREATE PROCEDURE SP_LISTAR_EMPLEADOS() 
BEGIN
    SELECT * FROM TB_EMPLEADO; 
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_INSERTAR_EMPLEADO(IN NOM VARCHAR(100)) 
BEGIN
    INSERT INTO TB_EMPLEADO(EMP_ID, EMP_NOMBRE) VALUES (NULL, NOM); 
END //
DELIMITER ;